# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('project', 'code')]),
        ),
    ]
