# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custodians',
            field=models.ManyToManyField(blank=True,
                                         help_text='Users that have write/upload access to the data of this project.',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='datum',
            field=models.IntegerField(blank=True,
                                      choices=[(4326, 'WGS84'), (4283, 'GDA94'), (4203, 'AGD84'), (4202, 'AGD66'),
                                               (28348, 'GDA94 / MGA zone 48'), (28349, 'GDA94 / MGA zone 49'),
                                               (28350, 'GDA94 / MGA zone 50'), (28351, 'GDA94 / MGA zone 51'),
                                               (28352, 'GDA94 / MGA zone 52'), (28353, 'GDA94 / MGA zone 53'),
                                               (28354, 'GDA94 / MGA zone 54'), (28355, 'GDA94 / MGA zone 55'),
                                               (28356, 'GDA94 / MGA zone 56'), (28357, 'GDA94 / MGA zone 57'),
                                               (28358, 'GDA94 / MGA zone 58')], default=4326,
                                      help_text='The datum all locations will be assumed to have unless otherwise specified.',
                                      null=True, verbose_name='Default Datum'),
        ),
    ]
