# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 07:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataDescriptor')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sitedataset',
            name='data_descriptor',
        ),
        migrations.RemoveField(
            model_name='sitedataset',
            name='site',
        ),
        migrations.AlterField(
            model_name='observation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.DeleteModel(
            name='SiteDataSet',
        ),
    ]
