# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 08:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='site_data_package',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Define here the attributes that all your sites will share. This allows validation when importing sites.', null=True, verbose_name='Site attributes schema'),
        ),
        migrations.AlterField(
            model_name='project',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='Australia/Perth', help_text="The Timezone of your project e.g 'Australia/Perth."),
        ),
    ]
