# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 04:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160820_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attributes_data_package',
        ),
        migrations.AddField(
            model_name='project',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='The boundary of your project (not required). Can also be calculated from the extents of the project sites', null=True, srid=4326, verbose_name='Extent'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="Define here all specific attributes of your project in the form of json 'attribute name': 'attribute value", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_data_package',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Define here the attributes that all your sites will share.', null=True, verbose_name='Site attributes schema'),
        ),
    ]
