# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160913_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
