# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericrecord',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='genericrecord',
            name='site',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='site',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='site',
        ),
        migrations.DeleteModel(
            name='GenericRecord',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='SpeciesObservation',
        ),
    ]
