# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 09:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160526_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data_descriptor',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='site',
        ),
        migrations.AlterField(
            model_name='datadescriptor',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('site', 'Site'), ('generic', 'Generic'), ('observation', 'Observation'), ('species_observation', 'Species observation')], default='generic', max_length=100),
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.AddField(
            model_name='genericrecord',
            name='data_descriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataDescriptor'),
        ),
        migrations.AddField(
            model_name='genericrecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AddField(
            model_name='genericrecord',
            name='src_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DataFile'),
        ),
    ]
