# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 06:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160715_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='attributes_descriptor',
            new_name='attributes_schema',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='data',
            new_name='attributes',
        ),
        migrations.RemoveField(
            model_name='site',
            name='dataset',
        ),
        migrations.AddField(
            model_name='site',
            name='attributes_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.CharField(choices=[('generic', 'Generic'), ('observation', 'Observation'), ('species_observation', 'Species observation')], default='generic', max_length=100),
        ),
    ]
