# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160920_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesobservation',
            name='input_name',
            field=models.CharField(blank=True, help_text='Species Name (as imported)', max_length=500, null=True, verbose_name='Species Name'),
        ),
    ]
