# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160526_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataDescriptor',
            new_name='DataSet',
        ),
    ]
