# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160920_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='input_name',
            new_name='species_name',
        ),
    ]
