# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160805_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='date_time',
            new_name='observation_date',
        ),
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='date_time',
            new_name='observation_date',
        ),
    ]
