# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_auto_20170512_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datum',
            field=models.IntegerField(blank=True,
                                      choices=[(4326, 'WGS84'), (4283, 'GDA94'), (4203, 'AGD84'), (4202, 'AGD66'),
                                               (28348, 'GDA94 / MGA zone 48'), (28349, 'GDA94 / MGA zone 49'),
                                               (28350, 'GDA94 / MGA zone 50'), (28351, 'GDA94 / MGA zone 51'),
                                               (28352, 'GDA94 / MGA zone 52'), (28353, 'GDA94 / MGA zone 53'),
                                               (28354, 'GDA94 / MGA zone 54'), (28355, 'GDA94 / MGA zone 55'),
                                               (28356, 'GDA94 / MGA zone 56'), (28357, 'GDA94 / MGA zone 57'),
                                               (28358, 'GDA94 / MGA zone 58'), (20348, 'AGD84 / MGA zone 48'),
                                               (20349, 'AGD84 / MGA zone 49'), (20350, 'AGD84 / MGA zone 50'),
                                               (20351, 'AGD84 / MGA zone 51'), (20352, 'AGD84 / MGA zone 52'),
                                               (20353, 'AGD84 / MGA zone 53'), (20354, 'AGD84 / MGA zone 54'),
                                               (20355, 'AGD84 / MGA zone 55'), (20356, 'AGD84 / MGA zone 56'),
                                               (20357, 'AGD84 / MGA zone 57'), (20358, 'AGD84 / MGA zone 58'),
                                               (20248, 'AGD66 / MGA zone 48'), (20249, 'AGD66 / MGA zone 49'),
                                               (20250, 'AGD66 / MGA zone 50'), (20251, 'AGD66 / MGA zone 51'),
                                               (20252, 'AGD66 / MGA zone 52'), (20253, 'AGD66 / MGA zone 53'),
                                               (20254, 'AGD66 / MGA zone 54'), (20255, 'AGD66 / MGA zone 55'),
                                               (20256, 'AGD66 / MGA zone 56'), (20257, 'AGD66 / MGA zone 57'),
                                               (20258, 'AGD66 / MGA zone 58')], default=4326,
                                      help_text='The datum all locations will be assumed to have unless otherwise specified.',
                                      null=True, verbose_name='Default Datum'),
        ),
    ]
