# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160526_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericrecord',
            old_name='data_descriptor',
            new_name='data_set',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='data_descriptor',
            new_name='data_set',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='data_descriptor',
            new_name='data_set',
        ),
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='data_descriptor',
            new_name='data_set',
        ),
        migrations.RemoveField(
            model_name='project',
            name='data_descriptor',
        ),
        migrations.AddField(
            model_name='project',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', related_query_name='data_set', to='main.DataSet'),
        ),
    ]
