# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160527_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericrecord',
            old_name='data_set',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='data_set',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='data_set',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='data_set',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='data_set',
            new_name='dataset',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='main.Project'),
        ),
    ]
