# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170619_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name'
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='comments',
            new_name='description'
        ),
        migrations.RenameField(
            model_name='site',
            old_name='comments',
            new_name='description'
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
