# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='speciesobservation',
            old_name='date',
            new_name='datetime',
        ),
    ]
