# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20160527_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DataSet')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='genericrecord',
            name='src_file',
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
