# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160811_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='genericrecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='project',
            name='datum',
            field=models.IntegerField(blank=True, choices=[(4326, b'WGS84'), (4283, b'GDA94'), (4203, b'AGD84'), (4202, b'AGD66'), (28350, b'GDA94 / MGA zone 50')], default=4326, help_text='The datum all locations will be assumed to have unless otherwise specified.', null=True, verbose_name='Default Datum'),
        ),
        migrations.AlterField(
            model_name='site',
            name='datum',
            field=models.IntegerField(choices=[(4326, b'WGS84'), (4283, b'GDA94'), (4203, b'AGD84'), (4202, b'AGD66'), (28350, b'GDA94 / MGA zone 50')], default=4326, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
    ]
