# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160527_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
