# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160818_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesobservation',
            name='uncertainty',
        ),
        migrations.AddField(
            model_name='speciesobservation',
            name='official_species_name',
            field=models.CharField(blank=True, help_text='The species name from the species database', max_length=500, verbose_name='Official Species Name'),
        ),
        migrations.AlterField(
            model_name='datasetfile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='genericrecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='input_name',
            field=models.CharField(help_text='Species Name as imported', max_length=500, verbose_name='Input Name'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='name_id',
            field=models.IntegerField(default=-1, help_text='The unique ID from the species database', verbose_name='Name ID'),
        ),
    ]
