# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160819_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesobservation',
            name='official_species_name',
        ),
        migrations.AlterField(
            model_name='datasetfile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='genericrecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
    ]
