# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160819_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='genericrecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dataset'),
        ),
        migrations.AlterField(
            model_name='speciesobservation',
            name='input_name',
            field=models.CharField(help_text='Species Name (as imported)', max_length=500, verbose_name='Species Name'),
        ),
    ]
