# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_create_default_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(help_text='The program this project belongs to.', on_delete=django.db.models.deletion.CASCADE, to='main.Program'),
        ),
    ]
