# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
