apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
secretGenerator:
  - name: biosys-env
    type: Opaque
    envs:
      - .env
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/biosys
    newTag: 1.1
