# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunisticobservation',
            name='datum',
            field=models.IntegerField(blank=True, choices=[(4326, b'WGS84'), (4283, b'GDA94'), (4203, b'AGD84'), (4202, b'AGD66'), (28350, b'GDA94 / MGA zone 50')], default=4326, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='trap',
            name='datum',
            field=models.IntegerField(blank=True, choices=[(4326, b'WGS84'), (4283, b'GDA94'), (4203, b'AGD84'), (4202, b'AGD66'), (28350, b'GDA94 / MGA zone 50')], default=4326, null=True, verbose_name='Datum'),
        ),
    ]
