# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20150623_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='trap_type',
            field=models.ForeignKey(blank='', on_delete=django.db.models.deletion.PROTECT, to='animals.TrapTypeLookup', verbose_name='Trap Type'),
        ),
    ]
