# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20160428_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='pouch',
            field=models.CharField(blank=True, choices=[('', ''), ('teats', 'teats'), ('pouch young', 'pouch young'), ('lactating', 'lactating')], default='', max_length=100, verbose_name='Pouch'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='svl',
            field=models.FloatField(blank=True, max_length=100, verbose_name='Head-Body'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='tail_length',
            field=models.FloatField(blank=True, max_length=50, verbose_name='Tail length'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='test_length',
            field=models.FloatField(blank=True, verbose_name='Testes length'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='test_width',
            field=models.FloatField(blank=True, verbose_name='Testes width'),
        ),
    ]
