# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20160428_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='svl',
            field=models.FloatField(blank=True, null=True, verbose_name='Head-Body'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='tail_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Tail length'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='test_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Testes length'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='test_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Testes width'),
        ),
    ]
