# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20160428_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='head_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Head length (mm)'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='pes_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Pes length (mm)'),
        ),
    ]
