# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20160428_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.AgeLookup', verbose_name='Age'),
        ),
    ]
