# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20160428_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='fate',
            field=models.CharField(blank=True, help_text='What happened to animal after trapping', max_length=100, verbose_name='Fate'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='reproductive_condition',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reproductive condition'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='trap_type',
            field=models.ForeignKey(blank='', null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.TrapTypeLookup', verbose_name='Trap Type'),
        ),
    ]
