# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_auto_20160428_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='pouch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pouch'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='tail_condition',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tail condition'),
        ),
    ]
