# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160415_1426'),
        ('animals', '0012_auto_20160428_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunisticobservation',
            name='site_visit',
        ),
        migrations.AddField(
            model_name='opportunisticobservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.LocationLookup', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='opportunisticobservation',
            name='observation_type',
            field=models.ForeignKey(blank=True, help_text='e.g: Bird', null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.ObservationTypeLookup', verbose_name='Observation Type'),
        ),
    ]
