# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20160429_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunisticobservation',
            name='accuracy',
            field=models.FloatField(blank=True, default=30.0, null=True, verbose_name='Accuracy (m)'),
        ),
    ]
