# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0009_auto_20150622_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratumspecies',
            name='avg_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Height (m)'),
        ),
    ]
