# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0011_auto_20160421_1641'),
        ('vegetation', '0010_auto_20160422_0904'),
    ]

    operations = [
    ]
