# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0012_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegobservation',
            name='comments',
            field=models.CharField(blank=True, max_length=500, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='pegobservation',
            name='erosion',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Erosion peg'),
        ),
    ]
