# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0013_auto_20160422_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disturbanceindicator',
            name='recently_burned_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Recently Burned Veg in %'),
        ),
        migrations.AlterField(
            model_name='disturbanceindicator',
            name='scorch_height',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Scorch Height m'),
        ),
        migrations.AlterField(
            model_name='disturbanceindicator',
            name='signs_damage_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Veg affected within Site %'),
        ),
    ]
