# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetation', '0014_auto_20160428_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetationvisit',
            name='site_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SiteVisit', verbose_name='Site Visit'),
        ),
    ]
