apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: biosys-deployment-hpa
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 250
      type: Resource
