apiVersion: apps/v1
kind: Deployment
metadata:
  name: biosys-deployment
  labels:
    app: biosys-deployment
spec:
  selector:
    matchLabels:
      app: biosys-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: biosys-deployment
    spec:
      containers:
      - name: biosys
        image: ghcr.io/dbca-wa/biosys
        imagePullPolicy: Always
        env:
        - name: ALLOWED_DOMAINS
          value: ".dbca.wa.gov.au"
        - name: CSRF_COOKIE_SECURE
          value: "True"
        - name: SESSION_COOKIE_SECURE
          value: "True"
        - name: SPECIES_FACADE_CLASS
          value: "main.utils_species.HerbieFacade"
        - name: TZ
          value: "Australia/Perth"
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 33
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
